// ═══════════════════════════════════════════════════════════════════════════════
//  ECONOMICS CSV EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

use std::io::Write;

use crate::economics::LeontiefResult;

/// Export Leontief simulation results to CSV.
///
/// Format:
///   - Header block with configuration and summary
///   - Convergence time-series (iteration, delta, l2_norm, total_output)
///   - Sector output table (index, name, demand, output, cascade_loss)
pub fn export_leontief_csv(result: &LeontiefResult, path: &str) -> anyhow::Result<()> {
    let mut f = std::fs::File::create(path)?;
    let cfg = &result.config;

    // ─── Header ─────────────────────────────────────────────────────────
    writeln!(f, "# FLUST LEONTIEF INPUT-OUTPUT SHOCK SIMULATION")?;
    writeln!(f, "# Generated by Flust v{}", env!("CARGO_PKG_VERSION"))?;
    writeln!(f, "#")?;
    writeln!(f, "# Sectors,{}", cfg.sectors)?;
    writeln!(f, "# Sparsity,{}", cfg.sparsity)?;
    writeln!(f, "# Spectral_target,{}", cfg.spectral_target)?;
    writeln!(f, "# Tolerance,{:.2e}", cfg.tolerance)?;
    writeln!(f, "# Max_iterations,{}", cfg.max_iterations)?;
    writeln!(f, "# Shock_sector,{}", cfg.shock_sector)?;
    writeln!(f, "# Shock_magnitude,{}", cfg.shock_magnitude)?;
    writeln!(f, "#")?;
    writeln!(f, "# Converged,{}", result.converged)?;
    writeln!(f, "# Iterations,{}", result.iterations)?;
    writeln!(f, "# Final_delta,{:.6e}", result.final_delta)?;
    writeln!(f, "# Multiplier,{:.6}", result.multiplier)?;
    writeln!(f, "# Spectral_radius_est,{:.6}", result.spectral_radius_est)?;
    writeln!(f, "# Computation_ms,{:.1}", result.computation_ms)?;
    writeln!(f, "# Total_matvec_ops,{}", result.total_matvec_ops)?;
    writeln!(f, "#")?;

    // ─── Convergence Series ─────────────────────────────────────────────
    writeln!(f, "# CONVERGENCE SERIES")?;
    writeln!(f, "iteration,delta,l2_norm,total_output,top_sector,top_sector_value")?;
    for snap in &result.snapshots {
        writeln!(
            f,
            "{},{:.6e},{:.6e},{:.6e},{},{:.6e}",
            snap.iteration,
            snap.delta,
            snap.l2_norm,
            snap.total_output,
            snap.top_sector,
            snap.top_sector_value,
        )?;
    }

    writeln!(f, "#")?;

    // ─── Sector Output Table ────────────────────────────────────────────
    writeln!(f, "# SECTOR OUTPUT TABLE")?;
    writeln!(f, "sector_index,sector_name,demand,output,cascade_loss")?;
    for i in 0..cfg.sectors {
        let name = if i < result.sector_names.len() {
            &result.sector_names[i]
        } else {
            "?"
        };
        writeln!(
            f,
            "{},{},{:.6e},{:.6e},{:.6e}",
            i,
            name,
            result.demand[i],
            result.output[i],
            result.sector_losses[i],
        )?;
    }

    Ok(())
}
