// ═══════════════════════════════════════════════════════════════════════════════
//  MDP KINEMATICS CSV EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

use std::io::Write;

use crate::kinematics::MdpResult;

/// Export MDP simulation results to CSV.
///
/// Format:
///   - Header block with configuration and summary
///   - Convergence series (iteration, exponent, norm_diff, max_entry_change)
///   - Steady-state distribution table (state, probability)
pub fn export_mdp_csv(result: &MdpResult, path: &str) -> anyhow::Result<()> {
    let mut f = std::fs::File::create(path)?;
    let cfg = &result.config;

    // ─── Header ─────────────────────────────────────────────────────────
    writeln!(f, "# FLUST MDP KINEMATICS SIMULATION")?;
    writeln!(f, "# Generated by Flust v{}", env!("CARGO_PKG_VERSION"))?;
    writeln!(f, "#")?;
    writeln!(f, "# Matrix_size,{}", cfg.matrix_size)?;
    writeln!(f, "# Sparsity,{}", cfg.sparsity)?;
    writeln!(f, "# Epsilon,{:.2e}", cfg.epsilon)?;
    writeln!(f, "# Max_iterations,{}", cfg.max_iterations)?;
    if let Some(seed) = cfg.seed {
        writeln!(f, "# Seed,{}", seed)?;
    }
    writeln!(f, "#")?;
    writeln!(f, "# Converged,{}", result.converged)?;
    writeln!(f, "# Iterations,{}", result.iterations)?;
    writeln!(f, "# Final_norm_diff,{:.6e}", result.final_norm_diff)?;
    writeln!(f, "# Spectral_gap,{:.6}", result.spectral_gap)?;
    writeln!(f, "# Peak_state,{}", result.peak_state)?;
    writeln!(f, "# Peak_probability,{:.6e}", result.peak_probability)?;
    writeln!(f, "# Computation_ms,{:.1}", result.computation_ms)?;
    writeln!(f, "# Total_multiplications,{}", result.total_multiplications)?;
    writeln!(f, "#")?;

    // ─── Convergence Series ─────────────────────────────────────────────
    writeln!(f, "# CONVERGENCE SERIES")?;
    writeln!(f, "iteration,exponent,norm_diff,max_entry_change,entropy")?;
    for snap in &result.snapshots {
        writeln!(
            f,
            "{},{},{:.6e},{:.6e},{:.6e}",
            snap.iteration,
            snap.exponent,
            snap.norm_diff,
            snap.max_entry_change,
            snap.steady_state_entropy,
        )?;
    }

    writeln!(f, "#")?;

    // ─── Steady-State Distribution ────────────────────────────────────
    writeln!(f, "# STEADY-STATE DISTRIBUTION")?;
    writeln!(f, "state,probability")?;
    for (i, &prob) in result.steady_state.iter().enumerate() {
        writeln!(f, "S{},{:.6e}", i, prob)?;
    }

    Ok(())
}
