// =============================================================================
//  COMPUTER VISION — CSV EXPORT
// =============================================================================

use std::io::Write;

use crate::vision::VisionResult;

/// Export vision pipeline results to CSV.
pub fn export_vision_csv(result: &VisionResult, path: &str) -> anyhow::Result<()> {
    let mut f = std::fs::File::create(path)?;
    let cfg = &result.config;

    // Header
    writeln!(f, "# FLUST IR VISION PROCESSING")?;
    writeln!(f, "# Generated by Flust v{}", env!("CARGO_PKG_VERSION"))?;
    writeln!(f, "#")?;
    writeln!(f, "# Input_rows,{}", cfg.input_rows)?;
    writeln!(f, "# Input_cols,{}", cfg.input_cols)?;
    writeln!(f, "# Upscale_factor,{}", cfg.upscale_factor)?;
    writeln!(f, "# Kernel,{}", cfg.kernel_type.label())?;
    writeln!(f, "# Kernel_size,{}", cfg.kernel_size)?;
    writeln!(f, "# Noise_level,{}", cfg.noise_level)?;
    if let Some(seed) = cfg.seed {
        writeln!(f, "# Seed,{}", seed)?;
    }
    writeln!(f, "#")?;
    writeln!(f, "# Output_rows,{}", result.output_rows)?;
    writeln!(f, "# Output_cols,{}", result.output_cols)?;
    writeln!(f, "# im2col_shape,{}x{}", result.im2col_rows, result.im2col_cols)?;
    writeln!(f, "# Computation_ms,{:.1}", result.computation_ms)?;
    writeln!(f, "# Upscale_ms,{:.1}", result.upscale_ms)?;
    writeln!(f, "# im2col_ms,{:.1}", result.im2col_ms)?;
    writeln!(f, "# GEMM_ms,{:.1}", result.gemm_ms)?;
    writeln!(f, "# Input_range,[{:.4},{:.4}]", result.input_min, result.input_max)?;
    writeln!(f, "# Output_range,[{:.4},{:.4}]", result.output_min, result.output_max)?;
    writeln!(f, "# SNR_dB,{:.2}", result.snr_estimate)?;
    writeln!(f, "#")?;

    // Output matrix
    writeln!(f, "# OUTPUT MATRIX ({}x{})", result.output_rows, result.output_cols)?;
    writeln!(f, "row,col,value")?;
    for i in 0..result.output_rows {
        for j in 0..result.output_cols {
            writeln!(f, "{},{},{:.6e}", i, j, result.output_matrix[i * result.output_cols + j])?;
        }
    }

    Ok(())
}
